/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.awt.Color;

/**
 *
 * @author Bavyan
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        
                       fpanel.setBackground(new java.awt.Color(0,0,84));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fpanel = new javax.swing.JPanel();
        bmg = new javax.swing.JButton();
        bsr = new javax.swing.JButton();
        wel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        msg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 84));
        setPreferredSize(new java.awt.Dimension(500, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 168, 76));
        jLabel1.setText("Grand Millennium Hotel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Management System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, -1));

        fpanel.setBackground(new java.awt.Color(0, 0, 84));
        fpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bmg.setBackground(new java.awt.Color(249, 246, 242));
        bmg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bmg.setForeground(new java.awt.Color(0, 0, 84));
        bmg.setText("Manage Guests");
        bmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmgActionPerformed(evt);
            }
        });
        fpanel.add(bmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        bsr.setBackground(new java.awt.Color(249, 246, 242));
        bsr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bsr.setForeground(new java.awt.Color(0, 0, 84));
        bsr.setText("Show Rooms");
        bsr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsrActionPerformed(evt);
            }
        });
        fpanel.add(bsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 160, -1));

        wel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wel.setForeground(new java.awt.Color(255, 255, 255));
        wel.setText("Welcome, Admin !");
        fpanel.add(wel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 150, 20));

        jPanel1.setBackground(new java.awt.Color(249, 246, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(0, 0, 84));
        jLabel4.setText("Total Rooms  :  50");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        fpanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 170, 50));

        jPanel3.setBackground(new java.awt.Color(249, 246, 242));
        jPanel3.setPreferredSize(new java.awt.Dimension(260, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 84));
        jLabel6.setText("Occupied  :  20");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        fpanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 170, 50));

        jPanel2.setBackground(new java.awt.Color(249, 246, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 84));
        jLabel5.setText("Available :  30");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        fpanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 170, 50));

        exit.setBackground(new java.awt.Color(249, 246, 242));
        exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 84));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        fpanel.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 160, -1));

        msg2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fpanel.add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, 30));

        getContentPane().add(fpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmgActionPerformed
msg2.setText("Guest section - Coming Soon !");
msg2.setForeground(Color.yellow);
        

// TODO add your handling code here:
    }//GEN-LAST:event_bmgActionPerformed

    private void bsrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsrActionPerformed
      
     msg2.setText("Rooms Section - Coming Soon !");
    msg2.setForeground(Color.red);



// TODO add your handling code here:
    }//GEN-LAST:event_bsrActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmg;
    private javax.swing.JButton bsr;
    private javax.swing.JButton exit;
    private javax.swing.JPanel fpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
