/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.management.system;

import java.awt.Color;

/**
 *
 * @author Bavyan
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        
                        getContentPane().setBackground(new java.awt.Color(0,0,84));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wel = new javax.swing.JLabel();
        bmr = new javax.swing.JButton();
        bmg = new javax.swing.JButton();
        bl = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        msg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 84));
        setPreferredSize(new java.awt.Dimension(500, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 246, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(0, 0, 84));
        jLabel4.setText("Total Rooms  :  50");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 25, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, 70));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 168, 76));
        jLabel1.setText("Grand Millennium Hotel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Managment System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, -1));

        wel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        wel.setForeground(new java.awt.Color(255, 255, 255));
        wel.setText("Welcom, Admin !");
        getContentPane().add(wel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 140, 30));

        bmr.setBackground(new java.awt.Color(249, 246, 242));
        bmr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bmr.setForeground(new java.awt.Color(0, 0, 84));
        bmr.setText("Manage Rooms");
        bmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmrActionPerformed(evt);
            }
        });
        getContentPane().add(bmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        bmg.setBackground(new java.awt.Color(249, 246, 242));
        bmg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bmg.setForeground(new java.awt.Color(0, 0, 84));
        bmg.setText("Manage Guests");
        bmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmgActionPerformed(evt);
            }
        });
        getContentPane().add(bmg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        bl.setBackground(new java.awt.Color(249, 246, 242));
        bl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bl.setForeground(new java.awt.Color(0, 0, 84));
        bl.setText("Back to Login");
        bl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blActionPerformed(evt);
            }
        });
        getContentPane().add(bl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(249, 246, 242));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 84));
        jLabel5.setText("Availabel  :  30");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 34, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 280, 70));

        jPanel3.setBackground(new java.awt.Color(249, 246, 242));
        jPanel3.setPreferredSize(new java.awt.Dimension(260, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(0, 0, 84));
        jLabel6.setText("Occupied  :  20");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 280, -1));

        exit.setBackground(new java.awt.Color(249, 246, 242));
        exit.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 84));
        exit.setText("Logout");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        msg2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(msg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmgActionPerformed
msg2.setText("Guest section - Coming Soon !");
msg2.setForeground(Color.yellow);
        

// TODO add your handling code here:
    }//GEN-LAST:event_bmgActionPerformed

    private void bmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmrActionPerformed
      
     msg2.setText("Rooms Section - Coming Soon !");
    msg2.setForeground(Color.red);



// TODO add your handling code here:
    }//GEN-LAST:event_bmrActionPerformed

    private void blActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blActionPerformed

loginform l = new loginform();
this.dispose();
l.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_blActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);


        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bl;
    private javax.swing.JButton bmg;
    private javax.swing.JButton bmr;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel msg2;
    private javax.swing.JLabel wel;
    // End of variables declaration//GEN-END:variables
}
